name: rama_app
description: An app to monitor traning of model. (Remote Analysis and Monitoring Application for ML models)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.7.0
  firebase_core: ^0.2.5+1
  flutter_spinkit: "^3.1.0"
  firebase_database: 1.0.3
  bezier_chart: "^1.0.10"
  progress_button: ^0.0.2
  wave: ^0.0.8
  fl_chart: ^0.1.5
  path_provider: 0.4.1
  barcode_scan: ^0.0.4
  qr_flutter: ^1.1.1

  intl: ^0.15.2
  timeago: ^2.0.16
  shimmer: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/images/user.jpg
    - assets/images/logo.png
  fonts:
     - family: Raleway
       fonts:
         - asset: fonts/Raleway-Regular.ttf
         - asset: fonts/Raleway-ExtraLight.ttf
         - asset: fonts/Raleway-Bold.ttf
           weight: 700
         - asset: fonts/Raleway-Italic.ttf
           style: italic


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
